version: '3'
services:
  api:
    image: sample-express-app
    build: .
    volumes:
        - .:/usr/src/app
    # networks:
    #   - backend
    ports:
      - "3000:9000"

  # web-cli:
  #   image: sample-express-app
  #   networks:
  #     - backend
  #   command: sh

# networks:
#   backend:
#     driver: bridge